name: AWS Test Environment

on:
  push:
    branches:
      - main

jobs:
  deploy_aws_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-west-2

      - name: Terraform Init
        run: terraform init -input=false -var-file=../environments/test/aws.tfvars

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=../environments/test/aws.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
