name: Azure Test Environment

on:
  push:
    branches:
      - main

jobs:
  deploy_azure_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login and Terraform Apply
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - run: terraform init -input=false -var-file=../environments/test/azure.tfvars
        working-directory: ./path/to/your/azure/terraform/configurations

      - run: terraform plan -input=false -var-file=../environments/test/azure.tfvars -out=tfplan
        working-directory: ./path/to/your/azure/terraform/configurations

      - run: terraform apply -input=false tfplan
        working-directory: ./path/to/your/azure/terraform/configurations
