name: Trigger Workflow by Comment

on:
  issue_comment:
    types:
      - created

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check Comment
        run: |
          if [[ ${{ github.event.comment.body }} == "/trigger-aws" ]]; then
            echo "Triggering AWS workflow..."
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/workflow-name-for-aws/dispatches \
            -d '{"ref": "main"}'
          elif [[ ${{ github.event.comment.body }} == "/trigger-gcp" ]]; then
            echo "Triggering GCP workflow..."
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/workflow-name-for-gcp/dispatches \
            -d '{"ref": "main"}'
          elif [[ ${{ github.event.comment.body }} == "/trigger-azure" ]]; then
            echo "Triggering Azure workflow..."
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/workflow-name-for-azure/dispatches \
            -d '{"ref": "main"}'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
