name: Trigger AWS

on:
  workflow_run:
    workflows: ["Terraform Deployment"]
    types:
      - completed

jobs:
  trigger_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS Deployment
        if: github.event.workflow_run.conclusion == 'success'
        run: |
          # Trigger the deploy_aws job in the main workflow
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci-cd.yml/dispatches \
          -d '{"ref": "main", "inputs": {"trigger": "deploy_aws"}}'
